export const trialType = {
  INIT: 'INIT',
};

export const signIn = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
};

export const apiCalls = {
  API_CALL_START: 'API_CALL_START',
  API_CALL_ERROR: 'API_CALL_ERROR',
};
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const actionTypes = {
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_FAILURE: 'GOOGLE_FAILURE',
  FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
  FACEBOOK_FAILURE: 'FACEBOOK_FAILURE',
};
