export const trialType = {
  INIT: 'INIT',
};

export const signIn = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
};

export const apiCalls = {
  API_CALL_START: 'API_CALL_START',
  API_CALL_ERROR: 'API_CALL_ERROR',
};
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const actionTypes = {
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_FAILURE: 'GOOGLE_FAILURE',
  FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
  FACEBOOK_FAILURE: 'FACEBOOK_FAILURE',
};

export const resetPassword = {
  CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
  CONFIRM_EMAIL_FAILURE: 'CONFIRM_EMAIL_FAILURE',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
};

export const articleActionTypes = {
  GET_ALL_ARTICLE_SUCCESS: 'GET_ALL_ARTICLE_SUCCESS',
  GET_ALL_ARTICLE_FAILURE: 'GET_ALL_ARTICLE_FAILURE',
};

export const articleDetailActionTypes = {
  GET_ONE_ARTICLE_SUCCESS: 'GET_ONE_ARTICLE_SUCCESS',
  GET_ONE_ARTICLE_FAILURE: 'GET_ONE_ARTICLE_FAILURE',
};

export const updateArticle = {
  UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
  UPDATE_ARTICLE_FAILURE: 'UPDATE_ARTICLE_FAILURE',
};
